import { jsPDF } from "jspdf";

export interface ProposalData {
  area: string;
  plant: string;
  name: string;
  email: string;
  signature?: string;
}

async function loadImageAsBase64(url: string): Promise<string> {
  const response = await fetch(url);
  const blob = await response.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}

export async function generateProposalPdf(data: ProposalData): Promise<Blob> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Load and add logo
  try {
    const logoBase64 = await loadImageAsBase64("/logo.png");
    const logoWidth = 50;
    const logoHeight = 30;
    const logoX = (pageWidth - logoWidth) / 2;
    doc.addImage(logoBase64, "PNG", logoX, 10, logoWidth, logoHeight);
  } catch {
    // Fallback to text if logo fails to load
    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(34, 139, 34);
    doc.text("AGRO", pageWidth / 2, 30, { align: "center" });
  }

  // Subtitle
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("Agricultural Proposals", pageWidth / 2, 48, { align: "center" });

  // Horizontal line
  doc.setDrawColor(34, 139, 34);
  doc.setLineWidth(0.5);
  doc.line(20, 55, pageWidth - 20, 55);

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("Proposal Details", pageWidth / 2, 75, { align: "center" });

  // Date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`Date: ${currentDate}`, pageWidth / 2, 85, { align: "center" });

  // Form fields
  const startY = 105;
  const lineHeight = 15;
  const labelX = 30;
  const valueX = 70;

  doc.setFontSize(12);

  const fields = [
    { label: "Area:", value: data.area },
    { label: "Plant:", value: data.plant },
    { label: "Name:", value: data.name },
    { label: "Email:", value: data.email },
  ];

  fields.forEach((field, index) => {
    const y = startY + index * lineHeight;

    // Label
    doc.setFont("helvetica", "bold");
    doc.setTextColor(50, 50, 50);
    doc.text(field.label, labelX, y);

    // Value
    doc.setFont("helvetica", "normal");
    doc.setTextColor(0, 0, 0);
    doc.text(field.value, valueX, y);
  });

  // Signature (if provided)
  if (data.signature) {
    const signatureY = 200;

    // Signature label
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(50, 50, 50);
    doc.text("Signature:", labelX, signatureY);

    // Signature image
    const signatureWidth = 80;
    const signatureHeight = 40;
    const signatureImageY = signatureY + 5;

    try {
      doc.addImage(
        data.signature,
        "PNG",
        labelX,
        signatureImageY,
        signatureWidth,
        signatureHeight
      );

      // Line under signature
      doc.setDrawColor(150, 150, 150);
      doc.setLineWidth(0.3);
      doc.line(labelX, signatureImageY + signatureHeight + 2, labelX + signatureWidth, signatureImageY + signatureHeight + 2);
    } catch (error) {
      console.error("Failed to add signature to PDF:", error);
    }
  }

  // Footer
  doc.setFontSize(9);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This document was automatically generated by Agro Proposals System",
    pageWidth / 2,
    280,
    { align: "center" }
  );

  // Return PDF as Blob
  return doc.output("blob");
}

// Helper to generate filename with random UUID for unpredictability
export function generatePdfFileName(name: string): string {
  const randomId = crypto.randomUUID().slice(0, 8);
  return `proposal_${name.replace(/\s+/g, "_")}_${randomId}.pdf`;
}
